/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SunshiDesert(props) {
  // @ts-ignore
  const { nodes, materials } = useGLTF("/index/sunshi-desert.glb");
  return (
    <>
      <fog attach="fog" args={["black", 0, 100]} />
      <group
        {...props}
        dispose={null}
        rotation={[0, Math.PI * 1.45, 0]}
        position={[1, -3, -11]}
        scale={[5, 5, 5]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Landscape001.geometry}
          material={materials["Material.001"]}
          position={[1.314, 1.048, 0.029]}
          scale={3.052}
        />
        <group position={[2.177, 0.585, -0.302]} scale={[0.094, 1.088, 0.094]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials["Material.006"]}
          position={[2.194, 0.036, -0.229]}
          rotation={[-0.026, 0, -0.047]}
          scale={0.404}
        />
        <group
          position={[2.321, 0.25, -0.425]}
          rotation={[Math.PI / 2, 0, 0.428]}
          scale={0.218}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh.geometry}
            material={materials.Ch15_body}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_1.geometry}
            material={materials.Ch15_body}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.007"]}
          position={[2.876, 0.266, 0.02]}
          scale={[0.079, 0.551, 0.079]}
        />
      </group>
    </>
  );
}

useGLTF.preload("/index/sunshi-desert.glb");
