/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Sunshi(props) {
  // @ts-ignore
  const { nodes, materials } = useGLTF("/index/sunshi-hall.glb", true, true);
  return (
    <>
      <fog attach="fog" args={["black", -20, 170]} />
      <group
        {...props}
        dispose={null}
        rotation={[0, Math.PI * 1.5, 0]}
        position={[-8, -10, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.columns}
          position={[-77.587, 62.339, -3.97]}
          rotation={[0, Math.PI / 2, 0]}
          scale={85.652}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.ground}
          position={[-68.08, 5.83, 54.894]}
          scale={[189.4, 6.348, 16.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.ground}
          position={[-81.885, -0.372, -4.743]}
          scale={[131.503, 55.306, 55.306]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials.ground}
          position={[-68.333, 5.83, -62.834]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[189.4, 6.348, 16.217]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials["concrete.002"]}
          position={[-35.633, 0.814, -9.262]}
          scale={[11.826, 9.749, 11.826]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Reception_sofa024.geometry}
          material={materials.Reception_sofa}
          position={[-29.74, 0.6, -9.598]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={34.954}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001.geometry}
          material={materials["Material.003"]}
          position={[-36.025, 10.587, -7.74]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={6.839}
        />
        <group
          position={[-13.748, 2.4, -7.547]}
          rotation={[Math.PI / 2, 0, 1.1]}
          scale={2.778}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh002.geometry}
            material={materials["Ch15_body.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_1.geometry}
            material={materials["Ch15_body.001"]}
          />
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/index/sunshi-hall.glb");
