name: Update Radio

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day
      timezone: "Europe/London"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: yarn
        working-directory: ./
        run: |
          yarn --no-package-lock

      - name: Update Radio
        working-directory: ./
        run: |
          node lib/radioLineup.js 

      - name: Check for changes
        id: check_changes
        run: |
          changes=$(git status --porcelain)
          if [ -n "$changes" ]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: commit changes if any
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m 'github-bot: update radio'
          git push
